# See LICENSE file for full copyright and licensing details.
{
    "name": "Tours and Travel Management System - All in one (with Portal)",
    "author": "Serpent Consulting Services Pvt. Ltd.",
    "maintainer": "Serpent Consulting Services Pvt. Ltd.",
    "summary": """Website of Tours and Packages""",
    "description": """This module allows manage tour and package bookings
        from website for any travels agency.""",
    "category": "website",
    "website": "http://www.serpentcs.com",
    "license": "AGPL-3",
    "version": "17.0.1.0.0",
    "sequence": 1,
    "depends": [
        "product",
        "website_crm",
        "portal_rating",
        "tour_travel_package_management",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/website_data.xml",
        "data/mail_template.xml",
        "views/package_view.xml",
        "views/hotel_facilities_view.xml",
        "views/testimonial.xml",
        "views/homepage.xml",
        "views/templates.xml",
        "views/packages.xml",
        "views/transportation.xml",
        # "views/hotels.xml",
        "views/hotel_details.xml",
        "views/visa.xml",
        "views/packages_details.xml",
        "views/package_dashboard.xml",
        "views/snippets.xml",
        "views/package_inquiry.xml",
        "views/hotel_inquiry.xml",
        "views/visa_inquiry.xml",
    ],
    "images": ["static/description/Banner_website_tour_agency.png"],
    "installable": True,
    "price": 365,
    "currency": "EUR",
    "assets": {
        "web.assets_frontend": [
            "website_tour_agency/static/src/css/owl.carousel.min.css",
            "website_tour_agency/static/src/css/owl.theme.default.min.css",
            "website_tour_agency/static/src/js/owl.carousel.min.js",
            "website_tour_agency/static/src/css/main.css",
            "website_tour_agency/static/src/css/main2.css",
            "website_tour_agency/static/src/js/common.js",
        ],
    },
}
