# See LICENSE file for full copyright and licensing details.
{
    "name": "Tours and Travel Management System - All in one (Except Portal)",
    "author": "Serpent Consulting Services Pvt. Ltd.",
    "maintainer": "Serpent Consulting Services Pvt. Ltd.",
    "summary": """Tours and Travel management system""",
    "category": "Tours & Travels",
    "website": "http://www.serpentcs.com",
    "license": "AGPL-3",
    "version": "17.0.1.0.2",
    "sequence": 1,
    "depends": [
        "tour_travel_crm",
        "tour_travel_hotel_management",
        "tour_travel_meal_management",
        "tour_travel_transportation",
        "tour_travel_ticket_management",
        "tour_travel_attraction_management",
        "tour_travel_extra_expenses",
    ],
    "data": [],
    "images": ["static/description/tour_travel_package_management.png"],
    "installable": True,
    "price": 1,
    "currency": "EUR",
}
